# Generated by Django 3.2.16 on 2023-11-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_create_congratulation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
